# Generated by Django 4.2.11 on 2025-12-29 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uploads", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resumeupload",
            name="missing_keywords",
            field=models.TextField(blank=True, null=True),
        ),
    ]
