# Generated by Django 4.2.11 on 2025-12-29 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uploads", "0002_resumeupload_missing_keywords"),
    ]

    operations = [
        migrations.AddField(
            model_name="resumeupload",
            name="ai_suggestions",
            field=models.TextField(blank=True, null=True),
        ),
    ]
